# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy docsraaghuio

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: false

      - name: install SSL
        working-directory: src/raaghuDocumentation.Web
        run: dotnet dev-certs https -v -ep authserver.pfx -p c4c2a05a-e4d0-484c-8273-cb4808b3877f
        
      - name: install abp cli
        run: dotnet tool install -g Volo.Abp.Cli --version 7.3.3 
        
      - name: install libs
        shell: pwsh
        run: abp install-libs

      - uses: microsoft/variable-substitution@v1
        with:
          files: 'src/raaghuDocumentation.DbMigrator/appsettings.json,src/raaghuDocumentation.Web/appsettings.json'
        env:
          ConnectionStrings.Default: ${{ secrets.CONNECTIONSTRINGS_DEFAULT_ABP }}
          App.SelfUrl: ${{ secrets.APP_SELFURL_ABP }}
          App.HealthCheckUrl: ${{ secrets.HEALTH_CHECK }}
          AuthServer.Authority: ${{ secrets.APP_SELFURL_ABP }}
          OpenIddict.Applications.raaghuDocumentation_Web.RootUrl: ${{ secrets.APP_SELFURL_ABP }}
          # Redis.Configuration: ${{ secrets.REDIS }}
          
      - name: dotnet publish
        working-directory: src/raaghuDocumentation.Web
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: DB Migration
        working-directory: src/raaghuDocumentation.DbMigrator
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/db

      - name: powershell
        shell: pwsh
        run: dotnet raaghuDocumentation.DbMigrator.dll
        working-directory: ${{env.DOTNET_ROOT}}/db

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'docsraaghuio'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AEA182255332418D937573A88616395D }}
          package: .
